CREATE TABLE USER_SESSIONS (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL UNIQUE,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	
	name varchar(100),
	photo_path text,	
	photo_type varchar(50),
	
	CONSTRAINT USER_SESSIONS_PK PRIMARY KEY (PRIMARY_ID)
);

 CREATE UNIQUE INDEX SPRING_SESSION_IX1_SESSION_ID ON USER_SESSIONS (SESSION_ID);
 CREATE INDEX SPRING_SESSION_IX2_EXPAIRY_TIME ON USER_SESSIONS (EXPIRY_TIME);
 CREATE INDEX SPRING_SESSION_IX3_PRINCIPAL_NAME ON USER_SESSIONS (PRINCIPAL_NAME);
 
 
 
 
 
 

CREATE SEQUENCE chat_id_seq
    START 1
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CYCLE;

CREATE TABLE CHATS(
	id bigint DEFAULT nextval('chat_id_seq') NOT NULL,
	producer_user_session_id CHAR(36) NOT NULL,
	consumer_user_session_id CHAR(36) NOT NULL,
	
	CONSTRAINT CHATS_PK PRIMARY KEY (id),
	CONSTRAINT CHATS_PRODUCER_SESSION_ID_FK  FOREIGN KEY (producer_user_session_id) REFERENCES USER_SESSIONS(SESSION_ID) ON DELETE CASCADE,
	CONSTRAINT CHATS_CONSUMER_SESSION_ID_FK  FOREIGN KEY (consumer_user_session_id) REFERENCES USER_SESSIONS(SESSION_ID) ON DELETE CASCADE	
);

CREATE INDEX chats_ix1_producer_user_session_id ON CHATS (producer_user_session_id);
CREATE INDEX chats_ix2_consumer_user_session_id ON CHATS (consumer_user_session_id);







CREATE SEQUENCE personal_messages_id_seq
    START 1
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CYCLE;

CREATE TABLE PERSONAL_MESSAGES(
	id bigint DEFAULT nextval('personal_messages_id_seq') NOT NULL,
	chat_id bigserial NOT NULL,
	sender_is_producer bool NO NULL,
	message text NOT NULL,
	send_time timestamp NOT NULL,
	
	CONSTRAINT PERSONAL_MESSAGES_PK PRIMARY KEY (id),
	CONSTRAINT PERSONAL_MESSAGES_CHAT_FK FOREIGN KEY (chat_id) REFERENCES CHATS(id) ON DELETE CASCADE
);

CREATE INDEX personal_messages_ix1_chat_id ON PERSONAL_MESSAGES (chat_id);







CREATE SEQUENCE public_messages_id_seq
    START 1
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CYCLE;

CREATE TABLE PUBLIC_MESSAGES(
	id bigint DEFAULT nextval('public_messages_id_seq') NOT NULL,
	producer_user_session_id char(36) NOT NULL,
	message text NOT NULL,
	send_time timestamp NOT NULL,
	
	CONSTRAINT PUBLIC_MESSAGES_PK PRIMARY KEY (id),
	CONSTRAINT PUBLIC_MESSAGES_PRODUCER_SESSION_ID_FK FOREIGN KEY (producer_user_session_id) REFERENCES USER_SESSIONS(SESSION_ID) ON DELETE CASCADE
);






CREATE TABLE USER_SESSIONS_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	
	CONSTRAINT USER_SESSIONS_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT USER_SESSIONS_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES USER_SESSIONS(PRIMARY_ID) ON DELETE CASCADE
);
